export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const FOUND_ILLEGAL_CHARACTER = 'FOUND_ILLEGAL_CHARACTER';

// Timer.
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const COUNT_TIMER = 'COUNT_TIMER';
export const TOGGLE_TIMER_IS_COUNTING = 'TOGGLE_TIMER_IS_COUNTING';
export const INCREMENT_INTERVAL_COUNT = 'INCREMENT_INTERVAL_COUNT';

export default {
  ADD_TASK,
  REMOVE_TASK,
  EDIT_TASK,
  FOUND_ILLEGAL_CHARACTER,
  START_TIMER,
  STOP_TIMER,
  COUNT_TIMER,
  TOGGLE_TIMER_IS_COUNTING,
  INCREMENT_INTERVAL_COUNT
}