const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const FOUND_ILLEGAL_CHARACTER = 'FOUND_ILLEGAL_CHARACTER';

// Timer.
const START_TIMER = 'START_TIMER';
const STOP_TIMER = 'STOP_TIMER';
const COUNT_TIMER = 'COUNT_TIMER';
const TOGGLE_TIMER_IS_COUNTING = 'TOGGLE_TIMER_IS_COUNTING';
const INCREMENT_INTERVAL_COUNT = 'INCREMENT_INTERVAL_COUNT';
const RESET_TIMER = 'RESET_TIMER';

export const ACTION_TYPES = {
  ADD_TASK,
  REMOVE_TASK,
  EDIT_TASK,
  FOUND_ILLEGAL_CHARACTER,
  START_TIMER,
  STOP_TIMER,
  COUNT_TIMER,
  TOGGLE_TIMER_IS_COUNTING,
  INCREMENT_INTERVAL_COUNT,
  RESET_TIMER
}

export default [
  ADD_TASK,
  REMOVE_TASK,
  EDIT_TASK,
  FOUND_ILLEGAL_CHARACTER,
  START_TIMER,
  STOP_TIMER,
  COUNT_TIMER,
  TOGGLE_TIMER_IS_COUNTING,
  INCREMENT_INTERVAL_COUNT,
  RESET_TIMER
];